---
title: "Intro"
author: "Erin"
date: "2025-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> This would be added into the report pdf which you can find in this section  
> If you want to see what the final product would look like, you can read main.pdf on the github.
> try inlcude code so I can add it into the appendix.  

## Erin's Section

When it comes to choosing an airline, safety is always concern for travellers. An airline with a previous record of crashes may steer passengers away, especially those that were high-profile in the media, but perhaps this is a flawed way of thinking. In an article titled “Should Travelers Avoid Flying Airlines That Have Had Crashes in the Past?”, Nate Silver explored this question using data collected over a 30-year period. He divided the data in half to work with two timeframes to see if past incidences are predictive of future ones. This allowed him conclude if it was reasonable for passengers to avoid airlines that have a previous record of recurring incidences. 
We took this same dataset to carry out our own analysis. Our data contained the names of 56 airlines based all over the world, along with their respective incidents, fatal incidents, and fatality counts, split in two groups between the years 1985-1999 and 2000-2014. We also included a variable of the available seat kilometres flown every week, which we used to standardize the dataset since airlines vary greatly in terms of how much they fly ensuring that the analysis was fair. This gave a much cleared idea of each airline’s relative safety record instead of being misled by differences in volume. 
One variable that was not in our original dataset but we knew would be interesting to include was the GDP of the country in which each airline is based. This gave us an insight into whether any correlation exists between GDP and incidences, that potentially occur due to funding-related issues. We did this by matching up the GDP with a variable we found in the ‘tsibbledata ‘package. 
We found Silver’s work interesting and wanted to build upon his analysis to determine whether previous incident history is indicative of future crashes.  
